### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Br1ght0ne** [enochtangg/quick-SQL-cheatsheet#7]
Hi, great work!

Just wanted to ask: do you want to include translations (like `README-lang.md`) in this repository, or I'm just better off having my own fork?

Some people wanted to have this in Russian, and I'm up for translating it.

**Comment by enochtangg** [comment]
Hey!
Yeah, that would be awesome if you're up for the challenge.

Thanks!

**Comment by blancogerardo94** [comment]
I would be happy to work on the Spanish translation

**Comment by enochtangg** [comment]
> I would be happy to work on the Spanish translation

@blancogerardo94  that would be great! Im sure that would help many
